if (WIN32)
    configure_file(inno_setup.iss.in inno_setup.iss)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/inno_setup.iss DESTINATION ${CMAKE_INSTALL_PREFIX}/packaging COMPONENT alcuin_lib)
elseif (APPLE)
    set(CPACK_PACKAGE_VERSION ${Alcuin_DOTTED_VERSION})
    set(CPACK_PACKAGE_VERSION_MAJOR ${Alcuin_VERSION_MAJOR})
    set(CPACK_PACKAGE_VERSION_MINOR ${Alcuin_VERSION_MINOR})
    set(CPACK_PACKAGE_VERSION_PATCH ${Alcuin_VERSION_PATCH})

    include(CPack)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_PACKAGE_NAME "AlcuinTestApp")
    set(CPACK_PACKAGE_PRODUCT_DESCRIPTION "A Test Application for the Graphical User Interface of the Alcuin Project")
    set(CPACK_ORG_NAME "Herbert Sauro's Sys-Bio Lab")
    set(CPACK_ORG_EMAIL "ad.heydarabadi@gmail.com")
    set(CPACK_PACKAGE_INSTALL_DIRECTORY "AlcuinTestApp")
    set(CPACK_PACKAGE_EXECUTABLES "AlcuinTestApp")
endif ()