name: Build Alcuin

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build_on_OSs:
    name: Build Alcuin on ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-12-release
            os_type: macos
            os_name: macos-12
            build_type: Release
          - name: macos-latest-release
            os_type: macos
            os_name: macos-latest
            build_type: Release
          - name: ubuntu-latest-release
            os_type: ubuntu
            os_name: ubuntu-latest
            build_type: Release
          - name: windows-latest-release
            os_type: windows
            os_name: windows-latest
            build_type: Release
        python_version: [ "3.11" ]
    runs-on: ${{ matrix.platform.os_name }}

    steps:
      - name: Checkout Alcuin
        uses: actions/checkout@v4

      - name: Set MSVC as the default compiler on Windows
        if: matrix.platform.os_type == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.6.0

      - name: Upgrade gcc on Linux
        if: matrix.platform.os_type == 'manylinux'
        shell: bash
        run: |
          if [ "${{ matrix.platform.os_type }}" == 'ubuntu' ]; then
            apt-get update
            apt-get install -y software-properties-common
            add-apt-repository -y ppa:ubuntu-toolchain-r/test
            apt-get update
            apt-get install -y gcc-11 g++-11
            update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90
            update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90
          elif [ "${{ matrix.platform.os_type }}" == 'manylinux' ]; then
            dnf install -y gcc-toolset-11
            scl enable gcc-toolset-11 bash
            echo "/opt/rh/gcc-toolset-11/root/usr/bin" >> "${GITHUB_PATH}"
          fi

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Get Host Architecture
        shell: bash
        run: |
          architecture=$(uname -m)
          echo "host_architecture=$architecture" >> "${GITHUB_ENV}"
          if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
            echo "OSX_ARCHITECTURES=$architecture" >> "${GITHUB_ENV}"
          fi

      - name: Install ccache
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
            brew install ccache
          elif [ "${{ matrix.platform.os_type }}" == 'ubuntu' ]; then
            sudo apt-get update
            sudo apt-get install -y ccache
          elif [ "${{ matrix.platform.os_type }}" == 'manylinux' ]; then
            mkdir -p ccache
            cd ccache
            curl -L https://github.com/ccache/ccache/releases/download/v4.9.1/ccache-4.9.1.tar.gz > ccache.tar.gz
            tar -zxf ccache.tar.gz
            rm ccache.tar.gz
            mkdir -p build-ccache
            mkdir -p install-ccache
            cd build-ccache
            cmake -DCMAKE_INSTALL_PREFIX="$RUNNER_WORKSPACE/ccache/install-ccache" -DCMAKE_BUILD_TYPE=Release ../ccache-4.9.1
            cmake --build . --target install
            echo "$RUNNER_WORKSPACE/ccache/install-ccache/bin" >> "${GITHUB_PATH}"
          fi

      - name: Prepare ccache timestamp on non-Windows platforms
        if: matrix.platform.os_type != 'windows'
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: Set ccache cache directory on non-Windows
        if: matrix.platform.os_type != 'windows'
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          echo "CCACHE_DIR=${RUNNER_WORKSPACE}/.ccache" >> "${GITHUB_ENV}"
          echo "COMPILER_LAUNCHER=ccache" >> "${GITHUB_ENV}"

      - name: Cache ccache files on non-Windows
        if: matrix.platform.os_type != 'windows'
        uses: actions/cache@v4
        with:
          path: ${RUNNER_WORKSPACE}/.ccache
          key:
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp
            }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
            ${{ runner.os }}-

      - name: Setup Python for non-Manylinux platforms
        if: matrix.platform.build_python == 'ON' && matrix.platform.os_type != 'manylinux'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Setup Python for Manylinux platforms
        if: matrix.platform.build_python == 'ON' && matrix.platform.os_type == 'manylinux'
        shell: bash
        run: |
          dnf install -y wget
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p /Miniconda3
          /Miniconda3/bin/conda create -y --name python${{ matrix.python_version }} python=${{ matrix.python_version }}
          /Miniconda3/bin/conda init && bash ~/.bashrc && . ~/.bashrc          cd ${RUNNER_WORKSPACE}
          echo "export PATH=/Miniconda3/envs/python${{ matrix.python_version }}/bin:$PATH" >> "${GITHUB_ENV}"

      #- name: Set Install Qt Configurations
      #  shell: bash
      #  run: |
      #    if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
      #      echo "HOMEBREW_NO_AUTO_UPDATE=1" >> "${GITHUB_ENV}"
      #    fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'

      - name: Create build directory
        shell: bash
        run: mkdir -p ${RUNNER_WORKSPACE}/build-alcuin

      - name: Configure CMake for Alcuin
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-alcuin
          cmake $GITHUB_WORKSPACE \
          -G "Ninja" \
          -DCMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_BUILD_TYPE=${{ matrix.platform.build_type }} \
          -DCMAKE_OSX_ARCHITECTURES=${OSX_ARCHITECTURES} \
          -DCMAKE_INSTALL_PREFIX="${RUNNER_WORKSPACE}/install-alcuin"

      - name: Build and install Alcuin
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-alcuin
          cmake --build . --target install --config ${{ matrix.platform.build_type }}

      - name: Create test-app build directory
        shell: bash
        run: mkdir -p ${RUNNER_WORKSPACE}/build-alcuin/test-app

      - name: Configure CMake for Alcuin Test App
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-alcuin/test-app
          cmake $GITHUB_WORKSPACE/test-app \
          -G "Ninja" \
          -DCMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_BUILD_TYPE=${{ matrix.platform.build_type }} \
          -DCMAKE_OSX_ARCHITECTURES=${OSX_ARCHITECTURES} \
          -DCMAKE_INSTALL_PREFIX="${RUNNER_WORKSPACE}/install-alcuin"

      - name: Build and install Alcuin Test App
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-alcuin/test-app
          cmake --build . --target install --config ${{ matrix.platform.build_type }}